//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_XML_Tutorial.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_XML_Tutorial.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;root&gt;
        ///  &lt;Tabs_XEDITOR&gt;UnitOperation,ActionPath,ValveState,PumpState,RockerState,MagnetState&lt;/Tabs_XEDITOR&gt;
        ///  &lt;UnitOperation&gt;
        ///    &lt;PathID&gt;
        ///    &lt;/PathID&gt;
        ///    &lt;ActionPath&gt;
        ///      &lt;help&gt;
        ///      &lt;/help&gt;
        ///      &lt;Source&gt;
        ///      &lt;/Source&gt;
        ///      &lt;Destination&gt;
        ///      &lt;/Destination&gt;
        ///      &lt;Via_Path&gt;
        ///      &lt;/Via_Path&gt;
        ///    &lt;/ActionPath&gt;
        ///    &lt;ValveState&gt;
        ///      &lt;help&gt;
        ///      &lt;/help&gt;
        ///      &lt;Valve1&gt;
        ///      &lt;/Valve1&gt;
        ///      &lt;Valve2&gt;
        ///      &lt;/Valve2&gt;
        ///      &lt;Valve3&gt;
        ///      &lt;/Valve3&gt;
        ///      &lt;Valve4&gt;
        ///      &lt;/Valve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnitOperationTemplate {
            get {
                return ResourceManager.GetString("UnitOperationTemplate", resourceCulture);
            }
        }
    }
}
